FROM enil/alpine-supervisord-onbuild

ENV JOBBER_URL https://github.com/dshearer/jobber/releases/download/v1.1/jobber-1.1-r0.apk

ADD $JOBBER_URL /tmp/jobber.apk

RUN apk add openrc bash --no-cache && \
    (apk add --allow-untrusted /tmp/jobber.apk ||:) && \
    rm -f /tmp/jobber.apk

# forward request and error logs to docker log collector
RUN ln -sf /dev/stdout /var/log/jobber.out.log
RUN ln -sf /dev/stderr /var/log/jobber.err.log
